CREATE TABLE role(
id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
role_name VARCHAR(50) NOT NULL
);

CREATE TABLE users(
id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
username VARCHAR(16) NOT NULL,
password VARCHAR(16) NOT NULL,
role_id INT FOREIGN KEY REFERENCES role(id)
);