//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTS.AuxClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class phone_number
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phone_number()
        {
            this.phone_number_customer = new HashSet<phone_number_customer>();
        }
    
        public int id { get; set; }
        public string full_number { get; set; }
        public string address { get; set; }
        public int phone_type_id { get; set; }
        public int ate_id { get; set; }
    
        public virtual ate ate { get; set; }
        public virtual phone_type phone_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phone_number_customer> phone_number_customer { get; set; }
    }
}
