//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTS.AuxClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class phone_number_customer
    {
        public int phone_number_id { get; set; }
        public int customer_id { get; set; }
        public Nullable<int> fee { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual phone_number phone_number { get; set; }
    }
}
